"""
report_builder.py

Mini Report Builder demo:
- Builder (interface) + ConcreteBuilders (HTML, Markdown)
- Director orchestrates a standard report composition
- Usage demo at bottom
"""
from abc import ABC, abstractmethod
from typing import List


# Product: Report (simple container for representation)
class Report:
    def __init__(self, title: str = ""):
        self.title = title
        # each section: {"heading":..., "body":...}
        self.sections: List[dict] = []
        self.footer: str = ""

    def add_section(self, heading: str, body: str):
        self.sections.append({"heading": heading, "body": body})

    def set_footer(self, footer: str):
        self.footer = footer


# Builder interface
class ReportBuilder(ABC):
    @abstractmethod
    def set_title(self, title: str) -> "ReportBuilder":
        pass

    @abstractmethod
    def add_section(self, heading: str, body: str) -> "ReportBuilder":
        pass

    @abstractmethod
    def set_footer(self, footer: str) -> "ReportBuilder":
        pass

    @abstractmethod
    def get_result(self) -> str:
        """Return built representation (e.g. HTML string, Markdown string)"""
        pass


# ConcreteBuilder: HTML
class HTMLReportBuilder(ReportBuilder):
    def __init__(self):
        self._report = Report()

    def set_title(self, title: str) -> "HTMLReportBuilder":
        self._report.title = title
        return self

    def add_section(self, heading: str, body: str) -> "HTMLReportBuilder":
        self._report.add_section(heading, body)
        return self

    def set_footer(self, footer: str) -> "HTMLReportBuilder":
        self._report.set_footer(footer)
        return self

    def get_result(self) -> str:
        parts: List[str] = []
        parts.append("<!doctype html>")
        parts.append("<html><head>")
        parts.append(
            f"<meta charset='utf-8'><title>{self._escape(self._report.title)}</title>")
        parts.append("</head><body>")
        parts.append(f"<h1>{self._escape(self._report.title)}</h1>")
        for sec in self._report.sections:
            parts.append(f"<h2>{self._escape(sec['heading'])}</h2>")
            parts.append(f"<p>{self._escape(sec['body']).replace('\\n','<br>')}</p>")
        if self._report.footer:
            parts.append(
                f"<footer>{self._escape(self._report.footer)}</footer>")
        parts.append("</body></html>")
        return "\n".join(parts)

    @staticmethod
    def _escape(text: str) -> str:
        # Very minimal escaping
        return (text.replace("&", "&amp;")
                    .replace("<", "&lt;")
                    .replace(">", "&gt;"))


# ConcreteBuilder: Markdown
class MarkdownReportBuilder(ReportBuilder):
    def __init__(self):
        self._report = Report()

    def set_title(self, title: str) -> "MarkdownReportBuilder":
        self._report.title = title
        return self

    def add_section(self, heading: str, body: str) -> "MarkdownReportBuilder":
        self._report.add_section(heading, body)
        return self

    def set_footer(self, footer: str) -> "MarkdownReportBuilder":
        self._report.set_footer(footer)
        return self

    def get_result(self) -> str:
        parts: List[str] = []
        if self._report.title:
            parts.append(f"# {self._report.title}\n")
        for sec in self._report.sections:
            parts.append(f"## {sec['heading']}\n")
            parts.append(f"{sec['body']}\n")
        if self._report.footer:
            parts.append(f"---\n{self._report.footer}\n")
        return "\n".join(parts)


# Director: orchestrates a standard report composition
class ReportDirector:
    def __init__(self, builder: ReportBuilder):
        self._builder = builder

    def build_daily_report(self, title: str, metrics: dict, notes: str):
        self._builder.set_title(title)
        # add a summary section
        summary_lines = [f"{k}: {v}" for k, v in metrics.items()]
        self._builder.add_section("Summary", "\n".join(summary_lines))
        # add notes section
        self._builder.add_section("Notes", notes)
        self._builder.set_footer("Generated by ReportDirector")
        return self._builder.get_result()


# Demo usage
if __name__ == "__main__":
    metrics = {"users": 1234, "errors": 3, "revenue": "$12,345"}

    # HTML
    html_builder = HTMLReportBuilder()
    director = ReportDirector(html_builder)
    html_report = director.build_daily_report(
        "Daily Report", metrics, "All systems nominal.")
    print("--- HTML Report ---")
    print(html_report[:400])  # print beginning

    # Markdown
    md_builder = MarkdownReportBuilder()
    director_md = ReportDirector(md_builder)
    md_report = director_md.build_daily_report(
        "Daily Report", metrics, "All systems nominal.")
    print("\n--- Markdown Report ---")
    print(md_report)
